
api.security.token.secret=my-secret-key-from-


hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

hibernate.connection.driver_class=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/Gestao-financeira-pessoal

spring.datasource.username=postgres

spring.datasource.password=ms1234

hibernate.show_sql=true

hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG